### ISSUE TITLE
Vue cli version 3

### ISSUE THREAD

**Issue by chiboreache** [richplastow/vue-veux-pug-coffee-stylus#1]
Hi!

Trying to set up coffee with vue-cli 3.1, but with no luck. 
I also tried just download your project, but it won't run either `~_~`

```
➜  vue-veux-pug-coffee-stylus git:(master) npm run dev

> n-a-m-e@1.0.0 dev /home/chibo/MEGA/Code/WEB/wvue/vue-veux-pug-coffee-stylus
> node build/dev-server.js

internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/chibo/MEGA/Code/WEB/wvue/vue-veux-pug-coffee-stylus/build/check-versions.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! n-a-m-e@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the n-a-m-e@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-23T19_37_36_750Z-debug.log

```

Hope you can help, since js is so ugly, so I just can't put up with it...

**Comment by chiboreache** [comment]
`npm i --save`
done the job! ^____^

but anyway - it would be nice if you update tutorial for the newer version 😉

**Comment by richplastow** [comment]
Heyy @chiboreache, you know I haven't looked at this project since I first created it!

I just got a Dependabot alert abot it, so that's why I’m looking here now. I’ll see if it’s worth upgrading deps, or whether to just let this repo rot :-D

**Comment by chiboreache** [comment]
@richplastow nevermind, i have another life now 😏
